version: "3"

services:
  spotlights:
    build:
      context: "../"
      dockerfile: development/Dockerfile
      args:
        IS_LOCAL_ENV: "true"
    hostname: spotlights
    container_name: spotlights
    env_file: ../config.env
    volumes:
      - ../:/code        
      - ../../cache:/data
    command: ./scripts/dev.sh
    ports:
     - 8081:8081
