version: '1.0'
stages:
  - checkout
  - package
  - test
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
    git: github
  spotlights_image:
    title: Building Spotlights Docker Image
    type: build
    stage: package
    image_name: spotlights
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: ./development/Dockerfile
  javascript_tests_image:
    title: Building Javascript Test Docker Image
    type: build
    stage: package
    image_name: javascripttests
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}-javascript
    dockerfile: ./testing/Dockerfile.node
  unit_test:
    title: Running Python Unit tests
    image: '${{spotlights_image}}'
    stage: test
    commands:
      - make linttest
  unit_test_javascript:
    title: Running Javascript Unit tests
    image: '${{javascript_tests_image}}'
    stage: test
    commands:
      - npm install && npm run lint-test
